// demos/angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { MediaRecorderService } from 'media-recorder/angular/dist/media-recorder';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-demo';

  constructor(private mediaRecorderService: MediaRecorderService) { 
    mediaRecorderService.foo();
  }
}

<style>
  .App {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .video-controls-container {
    display: flex;
    flex-direction: column;
    width: 20%;
  }

  .media-element {
    border: 1px solid black;
  }
</style>

<div>
  <app-video-preview></app-video-preview>
  <app-audio-preview></app-audio-preview>
</div>

// demos/vue-demo/src/App.vue
<template>
  <div id="app" class="App">
    <VideoDemo />
    <AudioDemo />
  </div>
</template>

<script>
import VideoDemo from './components/VideoDemo.vue'
import AudioDemo from './components/AudioDemo.vue'

export default {
  name: 'App',
  components: {
    VideoDemo,
    AudioDemo
  }
}
</script>

<style>
.App {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.video-controls-container {
  display: flex;
  flex-direction: column;
  width: 20%;
}

.media-element {
  border: 1px solid black;
}
</style>
